package ru.derendiaev.view;

import com.intellij.uiDesigner.core.Spacer;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.Action;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JPanel;
import lombok.Getter;

/**
 * Created by DDerendiaev on 14-Jan-22.
 */
public class Form implements PropertyChangeListener {

  private static final String START_BUTTON_TEXT = "START";
  private static final String STOP_BUTTON_TEXT = "STOP";

  private JPanel mainPanel;
  private JButton startStopButton;

  @Getter
  private GameField gameField;

  @Override
  public void propertyChange(PropertyChangeEvent evt) {
    String eventName = evt.getPropertyName();

    if (eventName.equals("stopGame")) {
      startStopButton.setText(START_BUTTON_TEXT);
    }
  }

  JPanel getMainPanel() {
    startStopButton.setText(START_BUTTON_TEXT);
    startStopButton.setPreferredSize(new Dimension(78, 30));
    startStopButton.addActionListener(new Action() {
      @Override
      public Object getValue(String key) {
        return null;
      }

      @Override
      public void putValue(String key, Object value) {

      }

      @Override
      public void setEnabled(boolean b) {

      }

      @Override
      public boolean isEnabled() {
        return false;
      }

      @Override
      public void addPropertyChangeListener(PropertyChangeListener listener) {

      }

      @Override
      public void removePropertyChangeListener(PropertyChangeListener listener) {

      }

      @Override
      public void actionPerformed(ActionEvent e) {
        if (startStopButton.getText().equals(START_BUTTON_TEXT)) {
          startStopButton.setText(STOP_BUTTON_TEXT);
          gameField.startGame();

        } else {
          startStopButton.setText(START_BUTTON_TEXT);
          gameField.stopGame();
        }
      }
    });

    return mainPanel;
  }

  //for CheckStyle: IDE generated methods
  private void createUIComponents() {
    gameField = new GameField(this);
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT edit this method OR
   * call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    createUIComponents();
    mainPanel = new JPanel();
    mainPanel.setLayout(new BorderLayout(1, 0));
    final JPanel panel1 = new JPanel();
    panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    panel1.setVisible(true);
    mainPanel.add(panel1, BorderLayout.SOUTH);
    startStopButton = new JButton();
    startStopButton.setHideActionText(false);
    startStopButton.setHorizontalAlignment(0);
    startStopButton.setText("");
    startStopButton.setVisible(true);
    panel1.add(startStopButton);
    final Spacer spacer1 = new Spacer();
    mainPanel.add(spacer1, BorderLayout.EAST);
    final Spacer spacer2 = new Spacer();
    mainPanel.add(spacer2, BorderLayout.WEST);
    gameField.setBackground(new Color(-16777216));
    gameField.setForeground(new Color(-4473925));
    gameField.setOpaque(true);
    gameField.setRequestFocusEnabled(true);
    mainPanel.add(gameField, BorderLayout.CENTER);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return mainPanel;
  }
}
